(define (sum_square_two a b c)
  (define (sum_of_square a b)
    (+ (* a a) (* b b)))
  (if (< a b)
      (if (< a c)
          (sum_of_square b c)
          (sum_of_square a b))
      (if (< b c)
          (sum_of_square a c)
          (sum_of_square a b))))
(sum_square_two 1 2 3)