(define (fast-product a b)
  (fast-iter a b 0))
(define (fast-iter a counter product)
  (if (= counter 0)
      product
      (if (even? counter)
          (fast-iter (double a) (halve counter) product)
          (fast-iter a (- counter 1) (+ a product)))))
(define (even? n)
  (= (remainder n 2) 0))
(define (double x)
  (+ x x))
(define (halve x)
  (/ x 2))
(fast-product 5 10000)