(define (product term a next b)
  (define (iter a result)
    (if (> a b)
      result
      (iter (next a) (* (term a) result))))
  (iter a 1))
(define (factorial n)
  (define (identity x) x)
  (define (inc x) (+ 1 x))
  (product identity 1 inc n))
(define (pi)
  (define (term1 a)
    (define (square x) (* x x))
    (/ (- (square a) 1) (square a)))
  (define (next1 a)
    (+ a 2))
  (* 4.0 (product term1 3 next1 199999)))
(pi)
