(define (cons a b)
  (* (expt 2 a)
     (expt 3 b)))

(define (divides? a b)
  (= (remainder b a) 0))
(define (extract-expt a n)
  (define (iter n acc)
    (if (divides? a n)
        (iter (/ n a) (+ acc 1))
        acc))
  (iter n 0))
(define (car n)
  (extract-expt 2 n))
(define (cdr n)
  (extract-expt 3 n))
(cons 2 3)
(cdr 108)